name: Sample-Workflow

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  Hi:
    runs-on: ubuntu-latest
    steps:
      - name: HI
        run: echo "HI THIS IS MAIN BRANCH WORKFLOW"
        shell: bash